[package]
name = "fastfinge-rs"
version = "0.1.0"
authors = ["ming li <mingyli34@gmail.com>"]
edition = "2018"

[lib]
name = "fastfingers"
path = "src/lib.rs"

[dependencies]
cursive = "0.13"
itertools = "0.8.2"
lazy_static = "1.4.0"
rand = "0.7"
