name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download dependencies
      run: sudo apt-get install libncurses5-dev libncursesw5-dev
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
